[package]
name = "spreadsheet-ods-formula"
version = "0.15.0"
authors = ["thomasscharler <thscharler@gmail.com>"]
edition = "2021"
description = "formula for use in spreadsheet-ods."
license = "MIT/Apache-2.0"
repository = "https://github.com/thscharler/spreadsheet-ods-formula"
readme = "README.md"
keywords = ["ODS", "spreadsheet", "OpenOffice", "LibreOffice"]
categories = ["parser-implementations"]
exclude = [".idea/*", ".gitignore"]

[lib]
name = "spreadsheet_ods_formula"

[[bin]]
name = "generate"
path = "generate_src/generate.rs"

[dependencies]
csv = "1.2.1"

[dependencies.spreadsheet-ods]
version = "0.17.0"
#path = "../spreadsheet-ods"
features = ["use_decimal", "all_locales"]
