[package]
name = "ods_formula3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.spreadsheet-ods]
path="../spreadsheet-ods"
features = [ "use_decimal", "all_locales" ]